### ISSUE TITLE
Setting interval time 

### ISSUE THREAD

**Issue by ramazanapa20** [capacitor-community/background-geolocation#1]
![image](https://user-images.githubusercontent.com/11804471/101132766-99a87080-3618-11eb-92e2-29bba3cc989a.png)

Hi, 
we use this plugin in our ionic/react project. It's working great but , we need set location every 30 seconds. In plugin default 1 second. We need property like setInvertal method. 

Thank you.

**Comment by diachedelic** [comment]
iOS does not provide a time interval filter, but both iOS and Android provide a distance filter. I want to keep behaviour consistent across platforms, so I would prefer to implement the latter. Would you consider using a distance filter instead?

**Comment by Zackery747** [comment]
Hello, @diachedelic. Great Plugin! Will you still consider adding the distance filter?

**Comment by diachedelic** [comment]
@Zackery747 yes, if that is something you would find useful.

**Comment by ramazanapa20** [comment]
I made my own filter using trigger. But plugin send every 1 second. It's bad for charging on our phones :)

**Comment by Zackery747** [comment]
@diachedelic I would find it super useful, as I need to track my users when they move around. 
The functionality I'm looking for is something that will get a new location if the user moved an X amount of meters from their last location without consuming a lot of battery power.

Anything similar would also be great. Thank you!

**Comment by diachedelic** [comment]
Available in v0.3.5

**Comment by Zackery747** [comment]
Thanks for adding the distance filter. I tested it this morning and it works great !!!
