### ISSUE TITLE
Do I have to stop watching when entering Foreground?

### ISSUE THREAD

**Issue by kzka90** [capacitor-community/background-geolocation#10]
Could you describe how the plugin works? I'm interested in only listening the location while being on background, does the Plugin already handles this? Does it only activate when App enters background mode, and stops when it enters foreground mode? Or do I have to detect this transitions myself and do `addWatcher` / `removeWatcher` accordingly?

**Comment by diachedelic** [comment]
For your use case, you will have to detect those transitions yourself. The plugin is capable of working in foreground-only by simply omitting the "backgroundMessage" option, but alas not background-only.
