### ISSUE TITLE
Android 13+ (API 33+) Needs runtime Notification Permission

### ISSUE THREAD

**Issue by deasurv** [capacitor-community/background-geolocation#102]
**Describe the bug**
For Android 13+ to work and have Ongoing notification of `BackgroundGeolocationService.java` properly, we need to prompt the runtime notification permission. in lower Android versions this has not been needed.

**To Reproduce**
If you set up and config the plugin correctly, it will have `Notification` access, but you should also check `Allow Notifications` manual from `App info` settings of your app.

**Expected behavior**
Plugin must be cared about runtime Notification Permission for Android 13+

**Smartphone (please complete the following information):**
 - Device: Galaxy S20 FE 5G (SM-G781B/DS)
 - OS: Android 13
 - One UI: 5.1

**Comment by diachedelic** [comment]
Is this not addressed in the README? https://github.com/capacitor-community/background-geolocation#android

**Comment by deasurv** [comment]
Yes, it is, but I don't know Java and Android too much, I don't know even where the runtime permission should be included in the code, in which file, which class, and which activity.
I mean it could be better if this case was handled by the plugin itself, if possible. or maybe a straightforward example.

**Comment by deasurv** [comment]
Thank you for your fast response
