### ISSUE TITLE
Check background location permission

### ISSUE THREAD

**Issue by jongbonga** [capacitor-community/background-geolocation#103]
**Is your feature request related to a problem? Please describe.**
Currently, with the capacitor Geolocation plugin, we can check for permission status but it does not provide status for background location. especially for Android.

This is from Sentry Diagnostics.
<img width="304" alt="Screenshot 2023-06-28 at 16 44 16" src="https://github.com/capacitor-community/background-geolocation/assets/12111716/41036910-b958-4b4c-937b-908cfa85b799">

**Describe the solution you'd like**
Can this plugin offer a way to check which permission is granted (coarse, fine or background)?

**Comment by alexandermccormick** [comment]
Just my two cents, but I believe you can use the [Capacitor Permissions](https://capacitorjs.com/docs/v2/apis/permissions) plugin to check which permissions have been granted.

As far as I know, this plugin doesn't use the `ACCESS_BACKGROUND_LOCATION` permission, but instead utilizes a foreground service. This is why there is a persistant notification. The `ACCESS_BACKGROUND_LOCATION` permission is a bit more intense, and requires you to send in a video explaining and demonstrating exactly how you use that permission.

**Comment by diachedelic** [comment]
That is correct. Don't worry about the background permission.

**Comment by jongbonga** [comment]
@alexandermccormick I did send a video demonstrating the use, but my user still experience issue tracking the location when the driver is an Android user, and I keep seeing the above issue on Sentry. 

and my options on the app look like 

```
{
  backgroundTitle: 'My App is tracking your trip.',
  backgroundMessage: 'My App is operating on the background.',
  distanceFilter: prodMode ? 2 : 0
}
```
So not sure how to handle it.

**Comment by diachedelic** [comment]
Some Android devices need battery saving optimizations disabled (via the Settings app) to reliably receive location updates in the background. Your Sentry report mentioning ACCESS_BACKGROUND_LOCATION is a red herring - this plugin does not need that permission.

**Comment by diachedelic** [comment]
What problem is your user experiencing exactly?

**Comment by jongbonga** [comment]
> Your Sentry report mentioning ACCESS_BACKGROUND_LOCATION is a red herring - this plugin does not need that permission.

I added it since I thought that was the reason I wasn't getting constant updates.

> What problem is your user experiencing exactly?

<img width="311" alt="Screenshot 2023-07-09 at 14 39 55" src="https://github.com/capacitor-community/background-geolocation/assets/12111716/bb71b847-8b3c-4999-ab78-934f40c817df">

The location is not being received or sent after a while.
I will remove `ACCESS_BACKGROUND_LOCATION` and try again and revert when I get updates

**Comment by diachedelic** [comment]
Make sure you are using the legacy bridge, otherwise location updates will stop after 5 minutes in the background on Android. https://github.com/capacitor-community/background-geolocation#android

**Comment by jongbonga** [comment]
> Make sure you are using the legacy bridge, otherwise location updates will stop after 5 minutes in the background on Android. https://github.com/capacitor-community/background-geolocation#android
<img width="346" alt="Screenshot 2023-07-10 at 11 03 43" src="https://github.com/capacitor-community/background-geolocation/assets/12111716/a53b5739-3a14-43f5-9e38-40e3dc7f62ea">

**Comment by diachedelic** [comment]
Are you familiar with the limitations on sending HTTP requests while the app is in the background? See https://github.com/capacitor-community/background-geolocation/issues/14#issuecomment-1293574693.

**Comment by jongbonga** [comment]
> Are you familiar with the limitations on sending HTTP requests while the app is in the background? See [#14 (comment)](https://github.com/capacitor-community/background-geolocation/issues/14#issuecomment-1293574693).

Yes, I use the capacitor [http plugin](https://capacitorjs.com/docs/apis/http). I'm busy testing with different devices to see if the issue is not our my server instead.

I will update asap.

**Comment by jongbonga** [comment]
Here are my findings:

1. The location data get sent for a while then "pause" until I open the app again only to receive a bunch of them at once
2. The notification shows but looks like it's the system notification and not the plugin's. I concluded so because the title & message are different from the one displayed. The title displayed says: `AppName is running` & the message: `Tap for more information or to stop the app`.

My plugin:
<img width="478" alt="Screenshot 2023-07-10 at 19 37 48" src="https://github.com/capacitor-community/background-geolocation/assets/12111716/ac7e33ab-1a45-4bcc-85a1-ba5d00ed9f3e">

My permissions
<img width="563" alt="Screenshot 2023-07-10 at 19 42 24" src="https://github.com/capacitor-community/background-geolocation/assets/12111716/44ddf08b-5f3e-4484-8fc6-f4a44652a10f">

My Capacitor config
<img width="182" alt="Screenshot 2023-07-10 at 19 43 40" src="https://github.com/capacitor-community/background-geolocation/assets/12111716/d80a3154-046b-4ab2-88a1-70b0ac37b4ae">

strings.xml
<img width="543" alt="Screenshot 2023-07-10 at 19 47 36" src="https://github.com/capacitor-community/background-geolocation/assets/12111716/6aedf82c-57c4-4ffd-9a00-e3b021f19e26">

Is there anything I could have missed?

**Comment by diachedelic** [comment]
I would say your problem is the notification. If the notification is not correctly configured, background location updates don't work properly. Make sure you've generated the icon correctly, using Android Studio:

```
    <!--
        The icon to use for the background notification. Note the absence of a
        leading "@". It defaults to "mipmap/ic_launcher", the app's launch icon.

        If a raster image is used to generate the icon (as opposed to a vector
        image), it must have a transparent background. To make sure your image
        is compatible, select "Notification Icons" as the Icon Type when
        creating the image asset in Android Studio.
    -->
    <string name="capacitor_background_geolocation_notification_icon">
        drawable/ic_tracking
    </string>
```

If the notification is misconfigured, it seems to open the Settings app when tapped, rather than your app.

**Comment by jongbonga** [comment]
> Make sure you've generated the icon correctly, using Android Studio

Let me try this. My icons are generated with the [capacitor assets](https://github.com/ionic-team/capacitor-assets) plugin

**Comment by jongbonga** [comment]
They were all there already. 
<img width="343" alt="Screenshot 2023-07-11 at 11 20 55" src="https://github.com/capacitor-community/background-geolocation/assets/12111716/d96e12d1-56c8-4be7-9c97-ab72b98bc6f3">

I will run and see if the notification appears after this.

**Comment by jongbonga** [comment]
I got the notification working.

I did this.
```
To make sure your image
        is compatible, select "Notification Icons" as the Icon Type when
        creating the image asset in Android Studio.
```

My mistake was the name of the icon that I did not set properly. I kept the one example from the example: `ic_tracking`

**Comment by diachedelic** [comment]
No worries, glad you got it working.
