### ISSUE TITLE
Android notification forwards to App Settings instead of App 

### ISSUE THREAD

**Issue by JMJHautier** [capacitor-community/background-geolocation#110]
**Describe the bug**
In Android, when I click on the background-tracking notification, I'm forwarded to the app-settings, and not to the app itself (as in iOs)

**To Reproduce**
1. On Android, set up notifications for background tracking
2. Launch your app and whatever processes that uses the plugin. 
3. Go in background mode
4. Click on the notification 

**Expected behavior**
I go back to the app (not to the settings) 

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 14

And thanks much for this plugin, it's great :-)

**Comment by diachedelic** [comment]
That happens when the notification icon is not correctly configured. Ensure you have configued the notification icon via Android Studio, details are in the README.

**Comment by diachedelic** [comment]
I was referring to the comment preceding `<string name="capacitor_background_geolocation_notification_icon">`.
