### ISSUE TITLE
Background geolocation Android 14 and ionic 7

### ISSUE THREAD

**Issue by danirm96** [capacitor-community/background-geolocation#116]
I'm developing an app with Ionic 7 and Angular 17. I'm trying to use background geolocation with BackgroundGeolocation (@capacitor-community/background-geolocation) for Android 14 through the plugin watcher, but after a few minutes (2/3), it stops emitting the location.

In the AndroidManifest.xml file, I've added:

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" /> <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" /> <uses-feature android:name="android.hardware.location.gps" />

And with the Geolocation plugin (@capacitor/geolocation), I'm requesting permissions using Geolocation.requestPermissions().then().catch();. According to the documentation, everything seems correct, but it stops emitting the location after a few seconds.

I've tried different code, but nothing seems to work. This is the closest I've gotten, where I managed to display the notification that it's collecting the location through the watcher.

**Comment by diachedelic** [comment]
So you are using @capacitor/geolocation alongside this plugin? That combo is known to cause at least one issue: https://github.com/capacitor-community/background-geolocation/issues/104. Calling `addWatcher` requests permissions by default, so you don't need @capacitor/geolocation for that. If you need a foreground watcher, omit `backgroundMessage` when calling `addWatcher`.

Make sure you faithfully follow [the installation instructions for Android](https://github.com/capacitor-community/background-geolocation?tab=readme-ov-file#android). Any misstep will cause background location updates to flake out.

Let me know how you go.
