### ISSUE TITLE
Notification icon still defaults to the white box even after providing the icon from mipmap

### ISSUE THREAD

**Issue by aditbharadwaj** [capacitor-community/background-geolocation#12]
**Describe the bug**
The feature update to have custom icon or per say default to app icon is not working as tested.
**To Reproduce**
going into background the notification which appears is still default white box. 

**Expected behavior**
Should take app icon by default or provided asset which can be mentioned in the strings.xml file.

**Screenshots**
![WhatsApp Image 2021-03-08 at 14 25 15](https://user-images.githubusercontent.com/6751554/110300008-619c3980-801c-11eb-9a7a-9df3aac70fb2.jpeg)
screenshot with still default icon

but when notification is pressed it shows the correct app icon then :
![WhatsApp Image 2021-03-08 at 14 37 14](https://user-images.githubusercontent.com/6751554/110300095-7f699e80-801c-11eb-945c-77c4b1c1c577.jpeg)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] One plus 7 pro 
 - OS: [e.g. iOS8.1] Android 10
 - Version [e.g. 22] plugin version 0.3.11

**Additional context**

**Comment by aditbharadwaj** [comment]
Also Clicking on notification opens the App Settings rather than the app main-activity which in turn should open the app.

https://user-images.githubusercontent.com/6751554/110301742-711c8200-801e-11eb-894b-c54ce37d2b0c.mp4

**Comment by aditbharadwaj** [comment]
reinstalling the package solved this issue

**Comment by aditbharadwaj** [comment]
the problem is solved , the asset used didnt follow the image asset rules for it 
**The notification in android must be transparent and have no background color!**
hope this helps someone

**Comment by diachedelic** [comment]
> The notification in android must be transparent and have no background color!

Do you mean the image? I would like to mention this in the documentation.

**Comment by aditbharadwaj** [comment]
> > The notification in android must be transparent and have no background color!
> 
> Do you mean the image? I would like to mention this in the documentation.

yes the image needs to be transparent and with  no background or the icon is shown as white box. We can check this when we right click on the res folder >> image asset >> and then in the drop down select notification icon and see weather the image selected is applicable or not. 😊
