### ISSUE TITLE
Ionic Capacitor - Start app at startup device

### ISSUE THREAD

**Issue by ikkettuvvoi** [capacitor-community/background-geolocation#122]
I'm not sure if it directly affects the plugin. I imagine this is a request made by others too but I couldn't find it in the forum.

To be able to start localization when the device starts, or start the application based on this plugin, there is any suggestion or guide?

**Comment by diachedelic** [comment]
I doubt that feature will ever be part of this plugin, just because I want to keep things simple. However, you might be interested in this paid plugin: https://www.transistorsoft.com/shop/products/capacitor-background-geolocation. It seems to do what you need.
