### ISSUE TITLE
Android HTTP Throttling

### ISSUE THREAD

**Issue by msacc-mas** [capacitor-community/background-geolocation#123]
Has anyone identified if the Android HTTP throttling in the background issue people have been reporting, _affects this plugin specifically?_ Or is this a known issue/feature with Android and _all_ HTTP requests in general?

I am asking because we are using Capactior/http plugin to get around this issue right now, but some of our analytics tools do not worth with the capacitor native http wrapper and if this issue is due to the plugin itself, we would need to identify that.

Follow up - what does "throttling" mean here - it limits how many times it can fire per time period? If so, whats the throttle rate?  In the issues on github, it seems like they are reporting it _stopping_ requests.

**Comment by diachedelic** [comment]
I believe it is a limitation of Chrome, introduced in v88. This page discusses throttling, but I believe the same policy change led to HTTP requests being stopped after 5 minutes in the background: https://developer.chrome.com/blog/timer-throttling-in-chrome-88.
