### ISSUE TITLE
WebSocket disconnects after 5 min

### ISSUE THREAD

**Issue by AramKuru** [capacitor-community/background-geolocation#124]
**Describe the bug**
I use WebSocket from web socket io. and it works in background for only 5 min is there any workaround or anything that I can do to fix this issue I know there is native http req but that does not handle WebSocket as far as I know.

**Expected behavior**
the app should run in background even after 5min
 
 
 
 - Device: Redmi note 8 pro 
 - OS: MIUI GLOBAL 12.5.8  ANDROID VERSION 11

**Comment by diachedelic** [comment]
The only solution I can think of is to write a Capacitor plugin that uses a native Websockets implementation.
