### ISSUE TITLE
Clicking on app notification open App info Settings page ?

### ISSUE THREAD

**Issue by aditbharadwaj** [capacitor-community/background-geolocation#13]
**Describe the bug**
Clicking on app notification open App info Settings page  is that intended ?

**To Reproduce**

**Expected behavior**
It should open the app main activity hence the app and not its info settings page

**Screenshots**
https://user-images.githubusercontent.com/6751554/110302060-d4a6af80-801e-11eb-974f-aa3441774cbb.mp4

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] one plus 7 pro
 - OS: [e.g. iOS8.1] android 10 
 - Version [e.g. 22] plugin version 0.3.11

**Additional context**

**Comment by aditbharadwaj** [comment]
reinstalling the plugin solved the issue

**Comment by diachedelic** [comment]
I belive this problem is actually caused by a missing icon, like you described in #12. Very strange I know.
