### ISSUE TITLE
Capacitor 3 Support

### ISSUE THREAD

**Issue by thomasvidas** [capacitor-community/background-geolocation#16]
### Is your feature request related to a problem? Please describe.
The Capacitor 3 RC is out! 🎉 This library should support the new version

### Describe the solution you'd like
Follow the plugin upgrade guide here: https://capacitorjs.com/docs/v3/updating/plugins/3-0

### Additional context
The migration is pretty easy, I've done it for a couple plugins. Happy to assist if you need assisting!

**Comment by diachedelic** [comment]
Yes I would like to, can I assume that any changes will be backward compatible with Capacitor v2?

If you wouldn't mind reviewing the source and suggesting the required changes, I would be most grateful. I expect the following source files will receive most or all of the required changes:

- https://github.com/capacitor-community/background-geolocation/blob/c413e721b739324d12e74e3f16b560b6c428fbb3/ios/Plugin/Plugin.swift#L59
- https://github.com/capacitor-community/background-geolocation/blob/c413e721b739324d12e74e3f16b560b6c428fbb3/android/src/main/java/com/equimaps/capacitor_background_geolocation/BackgroundGeolocation.java#L36

Thanks!

**Comment by thomasvidas** [comment]
Capacitor 3 has breaking changes for 2.x plugins, with the biggest ones being the import style and Android permissions, so it is difficult to maintain backwards compatibility. Here is what I would suggest (and have seen other developers do)

- Make `master` the 3.x branch and put the existing code into a `2.x` branch. Makes it easy to backport critical fixes/features!
- Release a new major version of you plugin and differentiate in your README something like _"versions 0.x are for Capacitor 2.x while versions 1.x+ are for Capacitor 3.x"_
- When publishing to npm, release with `npm publish --tag next` to prevent users from accidentally installing the version with Capacitor 3 changes until Capacitor 3 has hit full release.

Looking over your code quickly here are the things I see that need to be addressed.

### iOS
- `call.success()` should be `call.resolve()` and `call.error()` should be `call.reject()` to better match their JS counterparts.
- `self.bridge` is now a weak reference, but using `self.bridge?.func()` _should probably_ be fine.
- With your watcher, it seems you should be using the new `keepAlive` pattern for plugin calls. This allows your to use `call.resolve()` multiple times. The docs on that [are here](https://capacitorjs.com/docs/v3/core-apis/saving-calls). You can keep using the existing `saveCall` function but it doesn't seem to fit your use case. It might look like this

```swift
@objc func GetBackgroundLocation(_ call: CAPPluginCall) {
    call.keepAlive = true
  
    // ... do things! ...
  
    call.resolve()
  
    // ... do things! ...
    
    call.resolve()
}
```

### Android
- Same as the `keepAlive` stuff as above, but on Android it is `call.setKeepAlive(true)`.
- `@NativePlugin` to `@CapacitorPlugin`. You don't need the permission request codes anymore! Whenever you want to handle a permission you use the `@PermissionCallback or `@ActivityCallback` annotation above your callback rather than handling it in `handleRequestPermissionsResult`. It might look something like this.

```java
@CapacitorPlugin(
    name = "BackgroundGeolocation",
    permissions = {
        @Permission(strings = { Manifest.permission.ACCESS_FINE_LOCATION }, alias = "location_permission")
    }
)
public class BackgroundGeolocationPlugin {
    @PluginMethod()
    public void GetBackgroundLocation(PluginCall call) {
        if (getPermissionState("location_permission") != PermissionState.GRANTED) {
            requestPermissionForAlias("location_permission", call, "myCoolPermissionCallback");
        } else {
            getLocationData(call);
        }
    }
    
    @PermissionCallback
    private void myCoolPermissionCallback(PluginCall call) {
        // This happens after OS level permission check
        if (getPermissionState("location_permission") == PermissionState.GRANTED) {
            getLocationData(call);
        } else {
            call.reject("Permission is required to get background location");
        }
    }
    
    private void getLocationData(PluginCall call) {
      // Get the location data
    }
}
```

**Comment by diachedelic** [comment]
Thanks, I am working through these issues.
