### ISSUE TITLE
Cannot find module "@capacitor/core/dist/esm/core-plugin-definitions"

### ISSUE THREAD

**Issue by sverdlov** [capacitor-community/background-geolocation#22]
**Describe the bug**
I use Capacitor v3 and got this error 

`Error: node_modules/@capacitor-community/background-geolocation/definitions.d.ts:1:26 - error TS2307: Cannot find module '@capacitor/core/dist/esm/core-plugin-definitions' or its corresponding type declarations.
import {CallbackID} from "@capacitor/core/dist/esm/core-plugin-definitions";
`

I notice CallbackID is deprecated now. And you must import it from '@capacitor/core/types'

**Comment by diachedelic** [comment]
This should be fixed in v1.0.2, please let me know if it is not.
