### ISSUE TITLE
Android Build failing with 'cannot find symbol call.setKeepAlive(true)'

### ISSUE THREAD

**Issue by T0BiD** [capacitor-community/background-geolocation#23]
I've built a simple Ionic App with Capacitor v3.

When trying to build this app with android studio, the build is failing with the following error:

```
@capacitor-community\background-geolocation\android\src\main\java\com\equimaps\capacitor_background_geolocation\BackgroundGeolocation.java:53: error: cannot find symbol
        call.setKeepAlive(true);
            ^
  symbol:   method setKeepAlive(boolean)
  location: variable call of type PluginCall
```

**Comment by diachedelic** [comment]
That's weird, Capacitor v3 definitely defines a method `setKeepAlive` on the type `PluginCall`, see [source](https://github.com/ionic-team/capacitor/blob/e5b53aa687a70938994802c7b1367cfcbb1e3811/android/capacitor/src/main/java/com/getcapacitor/PluginCall.java#L358).

Is the method present in the `PluginCall.java` file in your project?

**Comment by T0BiD** [comment]
It seems like I did something wrong while setting up the project / Capacitor v3.
I created a new project from scratch and the error does not appear anymore.
