### ISSUE TITLE
Can the callback function perform network requests?

### ISSUE THREAD

**Issue by msacchetti** [capacitor-community/background-geolocation#24]
Does the watcher callback function allow POST requests? (Fetch, xhr, axios, etc)

**Comment by diachedelic** [comment]
See #14 for a discussion. You may need to use the Http plugin if you need it to send requests in the background, rather than XHR.

**Comment by msacchetti** [comment]
I tested version 0.3 with capacitor 2 and Axios post requests work in the background on android.
