### ISSUE TITLE
[Question] Is the notification on android always shown, or only while the task is run?

### ISSUE THREAD

**Issue by jesperbjerke** [capacitor-community/background-geolocation#25]
I don't need very accurate location, and only need to update it like once in a while from the background. What I can't figure out is if the notification for android is only shown the short duration while the location is updated, or all the time as long as the service is active?

**Comment by diachedelic** [comment]
The notification is shown if at least one watcher exists, and the app is not in the foreground. Showing the notification makes it possible to receive foreground location updates even while the app is in the background. Confusing, this is not the same as "real" background location updates on Android, which are only provided a few times an hour. You may want to look into that, see https://developer.android.com/training/location/background.

**Comment by jesperbjerke** [comment]
Okay, thanks for the info! Any plans on implementing an option for only listening on that kind of background location for this plugin?

**Comment by diachedelic** [comment]
If it was possible to implement consistently across Android and iOS, I would consider it. I do not have the time to implement such a feature myself, however.

**Comment by diachedelic** [comment]
See #19.
