### ISSUE TITLE
[Question] Is it possible to keep getting location updates when the app is closed?

### ISSUE THREAD

**Issue by marsnebulasoup** [capacitor-community/background-geolocation#26]
After some testing on Android it seems like the location updates are sent only as long as the app is open, though it doesn't have to be visible. I'm wondering if it is possible for the watcher to persist if the user, say, accidentally closes the app? Is this something already possible with this plugin, or would it have to be implemented?

Thanks

**Comment by diachedelic** [comment]
Hi @marsnebulasoup , I have tried to address this [here](https://github.com/capacitor-community/background-geolocation/issues/19).
