### ISSUE TITLE
Error: "BackgroundGeolocation" plugin is not implemented on android

### ISSUE THREAD

**Issue by gine** [capacitor-community/background-geolocation#28]
**Describe the bug**
Starting the geolocation i recive in Logcat this error
```
E/Capacitor/Console: File: http://localhost/static/js/4.b5a04f7e.chunk.js - Line 2 - Msg: Uncaught (in promise) Error: "BackgroundGeolocation" plugin is not implemented on android
```

**To Reproduce**
Follow your step to install it and this howto to solve a [compilation problem](
https://forum.ionicframework.com/t/ionic-capacitor-3-with-capacitor-community-background-geolocation-fails-to-run-in-android/209965/3)

**Smartphone (please complete the following information):**
 - OS: Android 30

**Comment by gine** [comment]
Manually adding add(BackgroundGeolocation.class); on 

```
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Add this line
      add(BarcodeScanner.class);
      add(BackgroundGeolocation.class);
    }});
  }
}
```
it start to work... maybe i had this problem because i had the overide here for BarcodeScanner?

**Comment by diachedelic** [comment]
So everything is OK?
