### ISSUE TITLE
No variants found on Android build

### ISSUE THREAD

**Issue by jongbonga** [capacitor-community/background-geolocation#29]
**Describe the bug**
I'm getting the exact same issue as #9 on version 1.0.2 for capacitor 3

Here is a snippet of the error log

No variants found for ':capacitor-community-background-geolocation'. Check build files to ensure at least one variant exists. at: com.android.tools.idea.gradle.project.sync.idea.svs.AndroidModule.deliverModels(AndroidModule.kt:191) com.android.tools.idea.gradle.project.sync.idea.svs.AndroidExtraModelProvider$Worker.populateBuildModels(AndroidExtraModelProvider.kt:121)

**To Reproduce**
Followed the installation instructions and run on Android

**Expected behavior**
To not run through a build error

**Smartphone (please complete the following information):**
 - Device: Android Studio 
 - OS: Android 30
 - Version 1.0.2

**Comment by diachedelic** [comment]
I would try this:

- Delete your node_modules directory
- Recreate your node_modules directory
- Run `npx cap sync`
- Run File -> "Sync Project with Gradle settings" in Android Studio

**Comment by diachedelic** [comment]
Additionally, you could try running Build -> "Clean Project" in Android Studio.

**Comment by jongbonga** [comment]
@diachedelic I have tried it dozens of time 🥲 cleared cache & restarted Android studio, removed the Android folder 🥲.

I have a couple of other plugins capacitor (intercom, barcode scanner, google map) that are syncing fine. Gradle fails the syncing when this one is in, but sync fine without it.

**Comment by diachedelic** [comment]
You say it's the exact same issue as #9: but do you also see the message _Error: package com.equimaps.capacitor_background_geolocation does not exist_ in the error log?

You might want to compare the value of `compileSdkVersion` in your app, your working plugins, and this plugin. See https://github.com/react-native-image-picker/react-native-image-picker/issues/1635

**Comment by jongbonga** [comment]
> You say it's the exact same issue as #9: but do you also see the message _Error: package com.equimaps.capacitor_background_geolocation does not exist_ in the error log?

<img width="302" alt="Screenshot 2021-07-07 at 16 07 07" src="https://user-images.githubusercontent.com/12111716/124773615-64ad2500-df3d-11eb-9e23-134f58f473ab.png">

**Comment by jongbonga** [comment]
> You might want to compare the value of `compileSdkVersion` in your app, your working plugins, and this plugin. See [react-native-image-picker/react-native-image-picker#1635](https://github.com/react-native-image-picker/react-native-image-picker/issues/1635)

I tried with 29 but nothing new happened

**Comment by diachedelic** [comment]
How about this: https://stackoverflow.com/a/67695836

**Comment by diachedelic** [comment]
Also, what do you see in the "Build Variants" panel?

**Comment by jongbonga** [comment]
> https://stackoverflow.com/a/67695836

I have both API levels 29 & 30 installed.

I didn't encounter any issue with capacitor v2 and corresponding plugin. since the upgrade, I'm unable to build

**Comment by jongbonga** [comment]
> Build Variants

Please help me locating the panel.

**Comment by jongbonga** [comment]
Went as far as to reinstall Android Studio but the error percists.

**Comment by diachedelic** [comment]
In the bottom left of your screenshot there is a "Build Variants" tab.

Try cloning this repository and running the application in the "example" directory. Then we can know if there is a problem with your project in particular, or your IDE.

**Comment by jongbonga** [comment]
> In the bottom left of your screenshot, there is a "Build Variants" tab.

<img width="1372" alt="Screenshot 2021-07-09 at 10 55 55" src="https://user-images.githubusercontent.com/12111716/125052437-4150ba00-e0a4-11eb-8b4e-4119991510fa.png">

> Try cloning this repository and running the application in the "example" directory. Then we can know if there is a problem with your project in particular or your IDE.

I tried and it worked fine, but also noticed capacitor is still in RC on the example (I'm haven't tried to update it)

**Comment by diachedelic** [comment]
This is what my Build Variants panel looks like:

![image](https://user-images.githubusercontent.com/310464/125054185-471cbe80-e0e9-11eb-8bba-5a410877f5f7.png)

Could you please trying upgrading Capacitor (in the cloned repo) to the latest version and seeing if the error manifests itself?

**Comment by jongbonga** [comment]
> I tried and it worked fine, but also noticed capacitor is still in RC on the example (I'm haven't tried to update it)

I just realized that I only test on iOS when adding this comment.

**Comment by jongbonga** [comment]
> Could you please trying upgrading Capacitor (in the cloned repo) to the latest version and seeing if the error manifests itself?

<img width="1392" alt="Screenshot 2021-07-09 at 12 04 11" src="https://user-images.githubusercontent.com/12111716/125061745-f20f8700-e0ad-11eb-8300-896830ee7c40.png">

Getting the same issue on a fresh clone, upgraded to Capacitor 3.1.1

**Comment by jongbonga** [comment]
Fresh clone, ran fine before and after updating Capacitor 😔

**Comment by diachedelic** [comment]
Then there must be an incompatibility between this plugin and your project. I can think of these approaches:
- Examine the difference between the build.gradle and app/build.gradle files of the example and of your project.
- Temporarily remove your other plugins.
- Add elements of your project (gradle files, plugins) to the example until it breaks.

**Comment by jongbonga** [comment]
> Also, what do you see in the "Build Variants" panel?
when I remove the plugin, this is what my build variants panel looks like
<img width="1392" alt="Screenshot 2021-07-09 at 22 59 15" src="https://user-images.githubusercontent.com/12111716/125135549-79d6af00-e109-11eb-9b4a-adfa0f33e6e4.png">

**Comment by jongbonga** [comment]
> * Examine the difference between the build.gradle and app/build.gradle files of the example and of your project.

The only difference is the example uses a "local version" of the plugins & mine comes from node_modules (which I don't think matters much).
And my Gradle version is 7.

I will try the other suggestions and revert with findings

**Comment by jongbonga** [comment]
I created a brand new project, only added this plugin and nothing else 
<img width="1392" alt="Screenshot 2021-07-10 at 11 31 00" src="https://user-images.githubusercontent.com/12111716/125158604-7592ac00-e172-11eb-87d3-b0f043dbed2b.png">

**Comment by ktoala** [comment]
Same error :/

**Comment by ktoala** [comment]
using this properties in variables.gradle the message disappear and compile successfully
ext {
    minSdkVersion = 21
    compileSdkVersion = 30
    targetSdkVersion = 30
    androidxActivityVersion = '1.2.0'
    androidxAppCompatVersion = '1.2.0'
    androidxBrowserVersion =  '1.3.0'
    androidxLocalbroadcastmanagerVersion =  '1.0.0'
    androidxCoordinatorLayoutVersion = '1.1.0'
    androidxCoreVersion = '1.3.2'
    androidxFragmentVersion = '1.3.0'
    playServicesLocationVersion =  '17.0.0'
    junitVersion = '4.13.1'
    androidxJunitVersion = '1.1.2'
    androidxEspressoCoreVersion = '3.3.0'
    cordovaAndroidVersion = '7.0.0'
}

But when call addWatcher the callback function return error with message `Service not running` i dont know what happen

**Comment by diachedelic** [comment]
How does that `variables.gradle` file differ from the default?

**Comment by jongbonga** [comment]
> How does that `variables.gradle` file differ from the default?

Mine didn’t have `androidxLocalbroadcastmanagerVersion`, `playServicesLocationVersion` & `androidxBrowserVersion` per default

**Comment by diachedelic** [comment]
I believe I have fixed this issue in release v1.0.3. Can you please test? You should not need to modify your `variables.gradle` file from the default.

**Comment by benedictcontawe** [comment]
I have this problem to in old projects

**Comment by Ozaoujal** [comment]
I have this problem too, I was in react-native v0.64.2, the problem occur when upgrading to react-native v0.71.8
