### ISSUE TITLE
registerPlugin not found

### ISSUE THREAD

**Issue by sander-spruit** [capacitor-community/background-geolocation#30]
After reading the docs, the plugin looked very promising, but cannot get it to work as of yet, likely due to unclear instructions. registerPlugin cannot be found (using capacitor V3).

1. Start new project using capacitor V3 (Angular + Ionic)
2. Run npm install @capacitor-community/background-geolocation, npx cap update
3. Attempt build

**Comment by diachedelic** [comment]
Please include the error output.

**Comment by sander-spruit** [comment]
./node_modules/@capacitor/core/dist/esm/index.js
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: ENOENT: no such file or directory, open '\node_modules\@capacitor\core\dist\esm\index.js'

"export 'registerPlugin' was not found in '@capacitor/core'

**Comment by diachedelic** [comment]
Your build system is misconfigured, and is resolving the "@capacitor/core" dependency to a non-existant file.

**Comment by sander-spruit** [comment]
I don't understand as everything else works properly. Seems the plugin instructions are unclear to me!
