### ISSUE TITLE
Capacitor 3 not registering pluging automatically

### ISSUE THREAD

**Issue by ramay2088** [capacitor-community/background-geolocation#33]
**Describe the bug**
I have upgraded from capacitor 2 to capacitor 3 . The issue I am facing on both plugins push notifications and background geolocation . Getting same error that is “Plugin not implemented for android”

According to the docs it should automatically register in MainActivity.java file but that is not happening I have to remove init method from that file
```
package siloc.xyz;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;

import java.util.ArrayList;
import com.hemangkumar.capacitorgooglemaps.CapacitorGoogleMaps;
import com.getcapacitor.community.bglocation.BackgroundGeolocation;
public class MainActivity extends BridgeActivity {

    @Override
    public void onCreate(Bundle savedInstanceState) {
      super.onCreate(savedInstanceState);
}

}

```
**To Reproduce**
I upgraded from capacitor 2 to capacitor 3

**Expected behavior**
It suppose to register these plugins

**Screenshots**

**Smartphone (please complete the following information):**
vivo v2029

**Comment by diachedelic** [comment]
I would try this:

- Delete your node_modules directory
- Recreate your node_modules directory
- Run npx cap sync
- Run Build -> "Clean Project" in Android Studio
- Run File -> "Sync Project with Gradle settings" in Android Studio
