### ISSUE TITLE
Add a example to use in typescript  

### ISSUE THREAD

**Issue by tripurarisingh1994** [capacitor-community/background-geolocation#35]
Hi,
   I have a request to you please add a example for the typescript that would be very helpful for us. 
I am adding code which given code snippet but getting error.

Thanks!

**Comment by diachedelic** [comment]
You can import the types as shown [here](https://github.com/capacitor-community/background-geolocation#typescript-support). Then, you follow the usage instructions [here](https://github.com/capacitor-community/background-geolocation#usage).
