### ISSUE TITLE
`backgroundMessage` and `backgroundTitle` and custom icon has no effect on notification

### ISSUE THREAD

**Issue by josiahbryan** [capacitor-community/background-geolocation#37]
**Describe the bug**
Passing `backgroundMessage` and `backgroundTitle` to `addWatcher` has no effect (does not change strings on the actual notification.) Also, the specified `<string>` (capacitor_background_geolocation_notification_icon) does not change the actual icon used. Also, touching the notification does NOT bring the app to foreground - instead it goes to app settings in the system UI.

**To Reproduce**
1. Install version 1.0.3 (latest from npm)
2. Call `.addWatcher` with custom `backgroundMessage` and `backgroundTitle` screens. Set `strings.xml` with custom icon
3. Put app in background
4. Check notification - see strings aren't set and icon is not set.
5. Touch the notification - see it goes to App Settings in System UI, not the actual app

**Expected behavior**
Title and body of notification should match strings given in item 2 above. Icon should batch documented icon in strings.xml. Touching the notification should open the app (bring to foreground)

**Screenshots**
Available on request

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: latest
 - Browser: Chrome
 - Version: Latest

**Additional context**
On request

**Comment by diachedelic** [comment]
How odd. Please set a breakpoint [here](https://github.com/capacitor-community/background-geolocation/blob/d8a9de45a69c9874261f93f9facf3c2bd0900e40/android/src/main/java/com/equimaps/capacitor_background_geolocation/BackgroundGeolocation.java#L81) and let me know what you find.

**Comment by josiahbryan** [comment]
@diachedelic not sure how to set a breakpoint on the plugin's java file - it doesn't show up as an available file in Android Studio when I do "shift shift" and search everything for "Background..." :) thoughts? 
![image](https://user-images.githubusercontent.com/4821548/135964597-bb0c2bb0-5ce4-4af9-9e69-10b9d988b4bc.png)

**Comment by diachedelic** [comment]
Looks like capacitor-background-geolocation is missing?

**Comment by josiahbryan** [comment]
It does look like that doesn't it? However it is listed in package.json and
it is working when access to be the plugin API, and I have ran npx cap sync
so not sure what else to do

**Comment by diachedelic** [comment]
Perhaps Build -> Clean Project in Android Studio?

**Comment by josiahbryan** [comment]
Good idea - that at least caused it to show up in the app tree. However, no change in functionality of the bug:
- Title/body/icon of notification still default - not responding to props (title/body) or manifest (icon)
- Clicking notification still goes to "App info" (system UI for force stopping/clearing cache/etc) instead of opening the app

Android studio tree now:
![image](https://user-images.githubusercontent.com/4821548/136071315-5a430c49-9377-4af7-83a9-1cb7107e08ab.png)

**Comment by diachedelic** [comment]
But you can set a breakpoint now.
