### ISSUE TITLE
Problem with typescript

### ISSUE THREAD

**Issue by dieyne** [capacitor-community/background-geolocation#5]
I can't import the plugin i get this error
```Cannot find module '@capacitor-community/background-geolocation' or its corresponding type declarations.```

**Comment by diachedelic** [comment]
What if you use `@capacitor-community/background-geolocation/definitions.d.ts`, does that work?

**Comment by dieyne** [comment]
I don't have  definitions.d.ts file in  @capacitor-community/background-geolocation

**Comment by diachedelic** [comment]
Please try again with v0.3.8.

**Comment by dieyne** [comment]
Now its ok, and i can import the plugin without definitions.d.ts

**Comment by diachedelic** [comment]
Fantastic!
