### ISSUE TITLE
Background stop when app is killed

### ISSUE THREAD

**Issue by tejadong** [capacitor-community/background-geolocation#52]
Hello:

I'm testing the connector and when the app is open in the foreground and in the background it works fine, but if I remove the app from my running app manager, the background stops working and I don't keep getting coordinates.

What's going on? Isn't the service supposed to stay active?

I am using Capacitor v3 and my Android version is 9 on my smartphone.

**Comment by diachedelic** [comment]
I've tried to address this in #19.
