### ISSUE TITLE
Blue bar behind clock on iOS

### ISSUE THREAD

**Issue by tylerclark** [capacitor-community/background-geolocation#60]
I would like my app to get and report background location much like Find My Friends. Apps like Uber or Google Maps (when it’s navigating) display a blue bar behind the clock which allows you to background the app and use other apps and click the clock to return. I want to do the same thing.

I thought this plug-in would do it when watching for background location but so far I haven’t seen it do it. Is what I want something else?

EDIT: Seems like this is called "showsBackgroundLocationIndicator". Has this been implemented? https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator

**Comment by diachedelic** [comment]
This is now the default behaviour in v1.2.0 and v0.3.15. Please test!
