### ISSUE TITLE
Which Android Versions are Supported?

### ISSUE THREAD

**Issue by BAyotte** [capacitor-community/background-geolocation#61]
**Is your feature request related to a problem? Please describe.**

Not necessarily a bug, but I am wondering which versions of android this is supported for. It is working for me on Android 11 but not on Android 9. Does this not work for less than or equal to 9?

**Describe the solution you'd like**

Would be really nice to support older versions of Android.

**Comment by diachedelic** [comment]
I'm not sure what version of Android are supported. I thought it worked on Android 8, but I no longer have an Android 8 device to test with. What happens on Android 9?
