### ISSUE TITLE
Using variables this. with vueJS

### ISSUE THREAD

**Issue by benjamin-ret** [capacitor-community/background-geolocation#62]
**Describe the bug**
Hi ! I want to use this.$i18n.t in function callback, but it's undefined ([error] - {})

**To Reproduce**
async mounted () {
...
function callback(location, error) {
...
console.log(this.$i18n.t('hello')
...

Any idea ? Thanks 

**Smartphone**
 - Device: iPhone SE2020
 - OS: iOS > 13

**Comment by diachedelic** [comment]
In JavaScript, `this` is dynamically bound. This means its value changes depending on how its containing function is called. Here, `this` does not refer to your component instance. Fortunately, you can save a reference to the component instance and use it later on:

async mounted () {
const vm = this;
...
function callback(location, error) {
...
console.log(vm.$i18n.t('hello')
...
