### ISSUE TITLE
Can not turn off background watch

### ISSUE THREAD

**Issue by emil-alexandrescu** [capacitor-community/background-geolocation#65]
**Describe the bug**
The background watch for location is turned on OS level. It seems like running removeWatcher won't turn it off.

**To Reproduce**
- Run addWatcher
- Run removeWatcher
- Background watch is still observable on OS level

**Expected behavior**
- Background watch should be abled to be turned off

**Screenshots**
![1](https://user-images.githubusercontent.com/7582371/167484993-1b1a2964-e130-4c2f-82e4-291ef0f42bec.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by diachedelic** [comment]
The addWatcher function no longer returns a watcher ID, it returns a Promise which resolves to a watcher ID. Check you are not passing a Promise to removeWatcher.

**Comment by emil-alexandrescu** [comment]
> The addWatcher function no longer returns a watcher ID, it returns a Promise which resolves to a watcher ID. Check you are not passing a Promise to removeWatcher.

We are already using proper watch ID and I can see it in logs, but it didn't help.

**Comment by diachedelic** [comment]
Can you please provide some more information, for example the device you are using, it's operating system, and the code which uses this plugin?

**Comment by wwwizzarrdry** [comment]
It doesn't stop the watcher on Android either. The only way to stop the watcher is to close the app completely.

**Comment by emil-alexandrescu** [comment]
@wwwizzarrdry thanks for your reply. We are using only one watcher, but the watcher times out after certain amount of time as well when the app is in background. Is it desired behavior?

**Comment by wwwizzarrdry** [comment]
I haven't had an issue on my Pixel 2 regarding the service dying in the background. Longest running process, so far, has been an 1hr:15min and everything worked fine - no disconnects in the logs.

**Comment by diachedelic** [comment]
@emil-alexandrescu Please contribute your specifics to https://github.com/capacitor-community/background-geolocation/issues/69.
