### ISSUE TITLE
iOS app not showing up in Settings

### ISSUE THREAD

**Issue by jeandemoroque** [capacitor-community/background-geolocation#66]
**Describe the bug**
I installed the plugin in my Ionic app (Vue3). I have a button that allows me to launch this plugin. When I click on it, I have the popup that appears asking me for permission to access the GPS coordinates.
1) If I accept the authorization, I receive the coordinates. But if I go to phone settings, I don't see my app. It is therefore impossible for the user to deactivate the authorization.
2) If I deny permission and click the button again, I call the "openSettings" function. I have the settings page that opens, but the application is not found. It is therefore impossible for the user to authorize access after having denied it.

**To Reproduce**
1. Install plugin in Ionic project (Vue3)
2. Compile iOS project
3. Open app and run plugin to display permissions alert
4. Deny the permissions
5. Run openSettings plugin function
6. Settings page is opening but the App is not found

**Smartphone:**
 - Device: iPhone 12 PRO (XCode simulator)
 - OS: iOS 15.4

**Comment by diachedelic** [comment]
Could you please try running it on a real device? The simulator is not always faithful to the real thing.

**Comment by flexiblefactory** [comment]
This appears to be still a problem. (On a real device)

**Comment by flexiblefactory** [comment]
@diachedelic I am wondering why was this was marked as "completed"? Still seems to be a problem (yes, on a real device).
Is this a capacitor problem, rather than a problem with the background location plugin?

**Comment by diachedelic** [comment]
If you app is not showing up in Settings -> Apps, that would be a problem with iOS.
