### ISSUE TITLE
iOS build error - Value of type 'CLLocation' has no member 'sourceInformation'

### ISSUE THREAD

**Issue by asiermusa** [capacitor-community/background-geolocation#67]
Does somebody know what I'm doing wrong with Xcode build for iOS. Every time I get this error:

<img width="1170" alt="Captura de pantalla 2022-05-12 a las 12 49 46" src="https://user-images.githubusercontent.com/32843723/168055938-c0d30edd-8ca0-47a8-8f36-4ede642c2af7.png">

I follow all the steps for iOS implementation, I change info.plist file and I ran required commands as npx cap sync/update.

For Android all the build works but not for iOS in my case.

**Ionic info:**

Ionic:

   Ionic CLI       : 6.17.0 (/Users/asiermusa/.nvm/versions/node/v15.2.1/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 6.1.4

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run                             : 1.5.0

System:

   NodeJS : v15.2.1 (/Users/asiermusa/.nvm/versions/node/v15.2.1/bin/node)
   npm    : 7.0.8
   OS     : macOS Big Sur

**Comment by diachedelic** [comment]
What version of Xcode are you using? I suspect it does not know about iOS 15.

**Comment by asiermusa** [comment]
My current Xcode version is Version 12.3 (12C33)

**Comment by diachedelic** [comment]
Xcode 12.3 only supports iOS versions up to 14. See if you are able to upgrade to Xcode 13.
