### ISSUE TITLE
A phone call or battery saver stops sending location to the server

### ISSUE THREAD

**Issue by namanambavi** [capacitor-community/background-geolocation#70]
The geolocation works in the background but when the device gets a phone call, the plugin stops sending an API request using the native HTTP module to the server. The notification is still seen on the device but we do not get the location pings.

Any solutions?

**Comment by diachedelic** [comment]
What device and operating system are you using?

**Comment by namanambavi** [comment]
It’s a Vivo phone running on Android 10

**Comment by jamesdiacono** [comment]
Do you have any other devices to test on? Perhaps the issue is device specific?

**Comment by namanambavi** [comment]
This issue looks like it's prevalent on all Vivo Device

**Comment by diachedelic** [comment]
Is the battery optimization feature definitely turned off?

**Comment by namanambavi** [comment]
Yes,
We have checked this twice and the optimization is off

**Comment by diachedelic** [comment]
I'm sorry, but I don't have a Vivo device to debug with. If you find a solution, please let me know.
