### ISSUE TITLE
Notification click back to app

### ISSUE THREAD

**Issue by basbroens** [capacitor-community/background-geolocation#77]
Hi all,

Really new to capacitor. But got everything working. 
I just wondered if it was possible to redirect a user back to the app using backgroundGeolocation?

I can edit the title and message.. but thats about it.

**Comment by diachedelic** [comment]
What happens when you tap the notification?

**Comment by basbroens** [comment]
Nothing :)

**Comment by diachedelic** [comment]
That's odd. Have you configured a notification icon via strings.xml?

**Comment by basbroensvz** [comment]
yes, however.. i removed the android folder en reinstalled it. Now everything is working as expected.
thank you for your help.
