### ISSUE TITLE
Background locations broken if distanceFilter enabled

### ISSUE THREAD

**Issue by PawelPlutaUek20** [capacitor-community/background-geolocation#87]
**Describe the bug**
addWatcher does not send the location if the distanceFilter option value is greater than 0.

**To Reproduce**
1. Set distanceFilter to any value greater than 0
2. The location is not sent in the background on android (it does in the foreground)

**Expected behavior**
send the location if the distance difference is greater than the specified value in distanceFilter

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Xiaomi redmi note 11
 - OS: [e.g. iOS8.1] Android 11

**Additional context**
- I also tested it on an emulated device (Android studio, Pixel 2 and Pixel 6a)
- works on ios
- works on android in the foreground
- works on android in the background ( but only if distanceFilter is 0 )

package.json:
```
{
    "@capacitor-community/background-geolocation": "^1.2.7",
    "@capacitor/android": "^4.6.2",
    "@capacitor/core": "^4.6.2",
    "@capacitor/ios": "^4.6.2",
}
```
additional capacitor plugins:
```
  plugins: {
    CapacitorHttp: {
      enabled: true,
    },
  },
```

**Comment by jamesdiacono** [comment]
I was not able to reproduce this problem with a distance filter of 10m, on my Samsung A52 running Android 12. Do you see the problem when you run the [example](https://github.com/capacitor-community/background-geolocation/tree/master/example) app?

**Comment by PawelPlutaUek20** [comment]
Thank you for the quick response, the error was actually caused by another plugin that I didn't have defined in the plugins (@capgo/capacitor-updater). I still didn't find the solution, but when I remove that plugin everything works fine. Great work btw!
