### ISSUE TITLE
Error: package com.equimaps.capacitor_background_geolocation does not exist

### ISSUE THREAD

**Issue by danielrf121** [capacitor-community/background-geolocation#9]
I installed the plugin, run CAP SYNC, but when importing it into MainActivity he doesn't find the plugin.

![Captura de Tela 2021-03-05 às 13 12 07](https://user-images.githubusercontent.com/15792968/110141966-6d85c280-7db4-11eb-84c4-2e124d8717ef.jpg)

**Comment by diachedelic** [comment]
I would expect "capacitor-community-background-geolocation" to appear in the project pane. I wonder why it doesn't?

**Comment by diachedelic** [comment]
Perhaps try running File -> "Sync Project with Gradle settings"?

**Comment by jaanreinok** [comment]
For me Android studio redlined dependency but after gradle install build ran successfuly but the red lines still remained until next restart. Everything worked like expected. Good readme.

**Comment by danielrf121** [comment]
Removing everything and installing again, when trying to synchronize with "Sync Project with Gradle Files" I got the following image error. Note that the plugin is not showing up there with the others in the project directories. In the other image it is possible to see that the capacitor finds the plugin at the time of the build, plays for "capacitor.build.gradle" but it is as if it were not on the project's premises.

capacitor.build.gradle

```
apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"
dependencies {
    implementation project(':capacitor-community-background-geolocation')
    implementation project(':rdlabo-capacitor-facebook-login')
    implementation project(':capacitor-apple-login')
    implementation project(':capacitor-firebase-analytics')
    implementation "com.android.support:support-v4:24.1.1+"
    implementation "com.onesignal:OneSignal:3.15.6"
    implementation "com.squareup.okhttp3:okhttp:3.12.0"
}
apply from: "../../node_modules/cordova-plugin-badge/src/android/badge.gradle"
apply from: "../../node_modules/onesignal-cordova-plugin/build-extras-onesignal.gradle"

if (hasProperty('postBuildExtras')) {
  postBuildExtras()
}
```

capacitor.settings.gradle

```
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')

include ':capacitor-community-background-geolocation'
project(':capacitor-community-background-geolocation').projectDir = new File('../node_modules/@capacitor-community/background-geolocation/android')

include ':rdlabo-capacitor-facebook-login'
project(':rdlabo-capacitor-facebook-login').projectDir = new File('../node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login')

include ':capacitor-apple-login'
project(':capacitor-apple-login').projectDir = new File('../node_modules/capacitor-apple-login/android')

include ':capacitor-firebase-analytics'
project(':capacitor-firebase-analytics').projectDir = new File('../node_modules/capacitor-firebase-analytics/android/capacitor-firebase-analytics')
```

![Captura de Tela 2021-03-08 às 11 37 21](https://user-images.githubusercontent.com/15792968/110336146-5688df80-8003-11eb-8824-af2d41e2aa66.jpg)

**Comment by diachedelic** [comment]
I have no idea what is causing this, please let me know if you find a solution.

**Comment by EpicVidak** [comment]
Have you added service into AndroidManifest.xml?

ex.
`
<application
        android:usesCleartextTraffic="true"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        
        <service
            android:name="com.equimaps.capacitor_background_geolocation.BackgroundGeolocationService"
            android:enabled="true"
            android:exported="true"
            android:foregroundServiceType="location" />

    </application>
`

**Comment by diachedelic** [comment]
This looks like an issue with Android Studio to me.

**Comment by msacchetti** [comment]
> Perhaps try running File -> "Sync Project with Gradle settings"?

This worked for me!

**Comment by jongbonga** [comment]
> Removing everything and installing again, when trying to synchronize with "Sync Project with Gradle Files" I got the following image error. Note that the plugin is not showing up there with the others in the project directories. In the other image it is possible to see that the capacitor finds the plugin at the time of the build, plays for "capacitor.build.gradle" but it is as if it were not on the project's premises.
> 
> **_OBS: For iOS works fine!_**
> 
> capacitor.build.gradle
> 
> ```
> apply from: "../capacitor-cordova-android-plugins/cordova.variables.gradle"
> dependencies {
>     implementation project(':capacitor-community-background-geolocation')
>     implementation project(':rdlabo-capacitor-facebook-login')
>     implementation project(':capacitor-apple-login')
>     implementation project(':capacitor-firebase-analytics')
>     implementation "com.android.support:support-v4:24.1.1+"
>     implementation "com.onesignal:OneSignal:3.15.6"
>     implementation "com.squareup.okhttp3:okhttp:3.12.0"
> }
> apply from: "../../node_modules/cordova-plugin-badge/src/android/badge.gradle"
> apply from: "../../node_modules/onesignal-cordova-plugin/build-extras-onesignal.gradle"
> 
> if (hasProperty('postBuildExtras')) {
>   postBuildExtras()
> }
> ```
> 
> capacitor.settings.gradle
> 
> ```
> include ':capacitor-android'
> project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')
> 
> include ':capacitor-community-background-geolocation'
> project(':capacitor-community-background-geolocation').projectDir = new File('../node_modules/@capacitor-community/background-geolocation/android')
> 
> include ':rdlabo-capacitor-facebook-login'
> project(':rdlabo-capacitor-facebook-login').projectDir = new File('../node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login')
> 
> include ':capacitor-apple-login'
> project(':capacitor-apple-login').projectDir = new File('../node_modules/capacitor-apple-login/android')
> 
> include ':capacitor-firebase-analytics'
> project(':capacitor-firebase-analytics').projectDir = new File('../node_modules/capacitor-firebase-analytics/android/capacitor-firebase-analytics')
> ```
> 
> ![Captura de Tela 2021-03-08 às 11 37 21](https://user-images.githubusercontent.com/15792968/110336146-5688df80-8003-11eb-8824-af2d41e2aa66.jpg)

I'm getting the exact same issue on `version 1.0.2` for `capacitor 3`

**Comment by wwwizzarrdry** [comment]
Sorry, but why was this issue closed? I have the same problem building for Android. 

My build fails with, "This dependency not met. You can install it with npm install @capacitor-community/background-geolocation", however, the module is clearly found in "src-capacitor/node_modules/@capacitor-community/".

I would love to know what's causing this error. 
I installed the native Geolocation capacitor plugin with no issues, but it seems that all the community plugins are broken in capacitor V3...
