### ISSUE TITLE
Custom setInterval and minUpdateInterval

### ISSUE THREAD

**Issue by CoooWeee** [capacitor-community/background-geolocation#90]
**Describe the bug**
Previously, I used the google location API and got really "good" _(fast update rate & okay precision)_ locations even if without GPS coverage.
Now, I am using this plugin with android and it seems as indoors or next to high-rise buildings I do not get often a location, and if the precision is not as good.
If I open my old APP or google maps the location immediately improves (precision & update rate).

It seems as if it does not do well with the fused location.
 

**To Reproduce**
1.
```
    self.gpsWatchId = await BackgroundGeolocation.addWatcher(
      {
        requestPermissions: true,
        stale: true,
        distanceFilter: 0,
      },
```
2. be somewhere inside where you do not have good GPS coverage but your google maps works.

**Version**
    "@capacitor-community/background-geolocation": "^1.2.7",

**Smartphone (please complete the following information):**
pixel 5

**Additional context**

**Comment by diachedelic** [comment]
What should we use instead of the fused location provider?

**Comment by CoooWeee** [comment]
I think the issue is that the intervals are not setable. 

**setWaitForAccurateLocation** is by default true but it seems only to work if the intervals are set accordingly. 

I changed over to **@capacitor/geolocation** but I think they have the same issue (https://github.com/ionic-team/capacitor-plugins/issues/538)
I think my suggestion would also work in this project:
https://github.com/ionic-team/capacitor-plugins/issues/538#issuecomment-1423423559

**Comment by diachedelic** [comment]
Are you saying that setting `setWaitForAccurateLocation` to false is not enough?

**Comment by CoooWeee** [comment]
> Are you saying that setting `setWaitForAccurateLocation` to false is not enough?

For my use case it has to be true. I want as high accuracy as I can get but want to fall back on non-gps if not available. 

I changed my previous comment to reflect what I'm using at the moment. That fixed it for me (fused location).

**Comment by diachedelic** [comment]
Are you saying that non-GPS locations are accurate enough for your purposes? What kind of accuracy readings do you get from them?

**Comment by CoooWeee** [comment]
> Are you saying that non-GPS locations are accurate enough for your purposes? What kind of accuracy readings do you get from them?

No, I'm saying they are not accurate enough but better than nothing.

**Comment by diachedelic** [comment]
But if you set `setWaitForAccurateLocation` to false, then the locations are too inaccurate for you?

**Comment by diachedelic** [comment]
Like, that is worse than nothing?

**Comment by diachedelic** [comment]
I noticed that in your watcher configuration, you set `stale: true` which implies that you want locations as soon as possible, regardless of their accuracy. I am thinking that the plugin should set `setWaitForAccurateLocation` to false when `stale` is true.

But with regards to your issue, are you saying that by adding

```
                     .setMinUpdateIntervalMillis(500)
                     .setMaxUpdateDelayMillis(1000)
```

the initial locations arrive faster?

**Comment by CoooWeee** [comment]
> But if you set `setWaitForAccurateLocation` to false, then the locations are too inaccurate for you?

Why would I? If I get a more accurate GPS position, I wanna wait for it and use it instead of the non-gps.

**Comment by diachedelic** [comment]
Sorry, I'm struggling to understand exactly what your priorities are. Please explain your position on the following:

- getting locations as fast as possible
- getting accurate locations
- getting more recent location readings, as opposed to stale
- getting locations via GPS vs. Wi-Fi (or however Google location services does it)
