### ISSUE TITLE
Upgrade iOS version to 13.0

### ISSUE THREAD

**Issue by Madserker** [capacitor-community/background-geolocation#91]
Hello, Im trying to implement this library in my Capacitor 4 project but it doesnt compile due to the minimum iOS version requirements. 
In Capacitor 4 it is set to be 13.0 in all plugins but in the podspec of this project it is set to 12.0.
`s.ios.deployment_target  = '12.0'`
Is there anyway to upgrade this to 13.0?

Thank you

**Comment by diachedelic** [comment]
Fixed in v1.2.9.

**Comment by Madserker** [comment]
Hello again @diachedelic sorry to bother you but it is possible that in the last update (1.2.14) the `s.ios.deployment_target  = '13.0'` went back to 12.0 again? cause it's giving me the same iOS error in this version. (In 1.2.9 its working fine though)

Thank you!

**Comment by diachedelic** [comment]
I changed it back to retain support for Capacitor v3. You can fix your build errors using something like this: https://stackoverflow.com/a/37289688/502846. When this plugin drops support for Capacitor v3, I will bump the deployment target to iOS 13.

**Comment by Madserker** [comment]
Thank you! That worked perfect! And one more thing i don't know if its my device or something im not handling well but i can't change the default background notification text with backgroundMessage and backgroundTitle. Is it not working for you either or its something related to my code?

thanks!

**Comment by diachedelic** [comment]
Most likely you have not configured the icon correctly. Follow the instructions here exactly: https://github.com/capacitor-community/background-geolocation#android.
