### ISSUE TITLE
Android Background icon issue in some devices

### ISSUE THREAD

**Issue by ivinantony** [capacitor-community/background-geolocation#93]
**Describe the bug**
Background Notification icon shows a square in some android devices. but i some devices it shows the correct icon as well

**To Reproduce**
Tested In Redmi 9 pro

**Expected behavior**
it should show the icon that we added in the strings.xml

**Screenshots**
![339758E5-F3D7-4C4E-AE98-267D0E6E799F](https://user-images.githubusercontent.com/66516836/221165081-88531869-4481-403f-9973-87bd6309f25c.jpg)

**Comment by diachedelic** [comment]
if you tap the notification, does it open the app or the settings? If it opens the settings that usually means the notification icon is configured incorrectly (weird, I know).

**Comment by diachedelic** [comment]
And make sure you create the icon using the tool in Android Studio, it has to be a specific format.

**Comment by ivinantony** [comment]
> And make sure you create the icon using the tool in Android Studio, it has to be a specific format.

thank you so much i have fixed it by creating the icon from android studuio
