### ISSUE TITLE
location speed value always 0 or some floated value

### ISSUE THREAD

**Issue by ivinantony** [capacitor-community/background-geolocation#96]
**Describe the bug**
this plugin works fine for me but the only issue is even i run ,walk or drive the speed seems 0 always.

**To Reproduce**
Install the app and put the app in background.
run or walk or drive.
check the value of the speed.

**Expected behavior**
the speed value should be updated when we drive or walk according =ly our spped
rtphone (please complete the following information):**
 Android and ios have this issue
**Additional context**

**Comment by diachedelic** [comment]
Can you please share what you did to fix this problem?
