### ISSUE TITLE
update POST Api every 5 minute

### ISSUE THREAD

**Issue by blinkdagger182** [capacitor-community/background-geolocation#97]
**Is your feature request related to a problem? Please describe.**
Earlier I was thinking of update my POST Api with user location every 5 minute so that i can detect if user is online or offline based of their last know location. If the last location of user is more than 5 minutes I will consider the user offline

**Describe the solution you'd like**
Maybe allow us to set interval for when watcher pings the api? Like similar for distance filter but based off time intervals.

**Describe alternatives you've considered**
I havent had any ideas as of yet ways to implement this based of the issues that I've of this plugin

**Additional context**

**Comment by diachedelic** [comment]
Duplicate of #34.
